services:
  duckling:
    image: rasa/duckling:latest
    ports:
      - 8000:8000
  rasa:
    image: aszych/iu_rasa_chatbot:0.0.5
    user: root
    build: 
      context: rasa_chatbot
    volumes:
      - "./rasa_chatbot:/app"
    ports: 
      - 5005:5005
  actions:
    image: aszych/iu_rasa_actions:0.0.7
    build: 
      context: rasa_chatbot/actionsdocke
    volumes:
        - ./rasa_chatbot/actions:/app/actions
        - ./rasa_chatbot/data:/app/data
    ports:
      - 5055:5055
  postgres:
    image: aszych/iu_rasa_database:0.0.3
    environment:
      POSTGRES_USER: rasa_user
      POSTGRES_PASSWORD: rasa_password
      POSTGRES_DB: rasa_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "rasa_db", "-U", "rasa_user"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
